
default: &default
  adapter: postgresql
  encoding: unicode
  username: developer
  password: 1234
  host: localhost
  port: 5432

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: SimpleChatRealTime_development

test:
  <<: *default
  database: SimpleChatRealTime_test


